# Generated by Django 6.0.2 on 2026-02-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
