# Generated by Django 6.0.2 on 2026-02-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='category',
            field=models.CharField(choices=[('Fitness', 'Fitness'), ('Coding', 'Coding'), ('Reading', 'Reading'), ('Health', 'Health'), ('Work', 'Work'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
