# Generated by Django 6.0.2 on 2026-02-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_alter_mission_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='category',
            field=models.CharField(choices=[('Fitness', 'Fitness'), ('Coding', 'Coding'), ('Reading', 'Reading'), ('Health', 'Health'), ('Education', 'Education'), ('Work', 'Work'), ('Gaming', 'Gaming'), ('Content Creation', 'Content Creation'), ('Travel', 'Travel'), ('Cooking', 'Cooking'), ('Music', 'Music'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
